### ISSUE TITLE
关于代码的公开问题

### ISSUE THREAD

**Issue by CQMUyan** [Brian-hongyan/DEG-substance-addiction#1]
请问一下代码什么时候公开？如果想学习一下拓扑数据分析，请问作者有什么推荐的入门资料吗？

**Comment by Brian-hongyan** [comment]
您好，文章的代码整理后会尽快公开。
推荐的资料：
http://outlace.com/TDApart1.html，这个博客从理论到实践介绍了persistent homology，讲的很好；
关于persistent Laplacian，推荐论文：
https://onlinelibrary.wiley.com/doi/abs/10.1002/cnm.3376

**Comment by CQMUyan** [comment]
谢谢您的帮助
